### ISSUE TITLE
NPM shasum fails on install

### ISSUE THREAD

**Issue by kayvon** [konsumer/easy-ffmpeg#1]
I've tried to npm install on several different machine. The following error occurs: 

Error: shasum check failed for /home/kayvon/tmp/npm-5484-I2pl8S5h/1437439300941-0.8788882563821971/tmp.tgz
From:     https://registry.npmjs.org/easy-ffmpeg/-/easy-ffmpeg-0.0.1.tgz

**Comment by MatthD** [comment]
Same error for me , How to use it ? :)

**Comment by konsumer** [comment]
This may be related to #2. I will update and see if it fixes it.
