### ISSUE TITLE
Update all binaries to 2.8 release

### ISSUE THREAD

**Issue by TheJaredWilcurt** [konsumer/easy-ffmpeg#2]
They should all be consistent and match, right now you're using a snapshot for Windows, 2.5 for Linux, and I don't even know for OSX.

If people are wanting to use this cross-platform (which is what I would the think the point of this repo is), they should be able to rely on matching versions from a stable (2.8) release.

**Comment by konsumer** [comment]
+1 I'm pretty busy right now, but I will set this up when I get a chance. Feel free to make a PR.

**Comment by konsumer** [comment]
I'd like to
