### ISSUE TITLE
True standalone?

### ISSUE THREAD

**Issue by swampthang** [konsumer/easy-ffmpeg#5]
When I saw this I thought, cool! - there is hope! But it's not working in a packaged app. Is this supposed to create true standalone versions of ffmpeg? No system file dependencies? I installed and get the same error as before. Need to be able to export PNG image sequences to various video fonrs - MP4, mov, etc.

I've been trying to figure out how to get ffmpeg to work in in my packaged app (electron) for almost 2 weeks. It works perfectly in dev of course. I have downloaded the static builds and placed them in the main directory. Using fluent-ffmpeg and have set the paths like so:

```
const ffmpeg = require('fluent-ffmpeg');
ffmpeg.setFfmpegPath('./ffmpeg');
ffmpeg.setFfprobePath('./ffprobe');
```

When I packaged the app and try to run it I get this...

```
Error: spawn ./ffmpeg ENOENT
    at exports._errnoException (util.js:949:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)
```

I've seen mention of linking to .dll, .so and .dylib. If that's true, where do I put these files and how do I link to them? From which file(s)?

The description says that easy-ffmpeg is a wrapper that "includes binaries". Where exactly are these binaries and are they automatically linked by simply running npm install easy-ffmpeg ?

I wondered if there was a way to config the --prefix variable to be the directory where the app is installed? Like in node using `__dirname`

**My info:**
Mac OS X Yosemite
Started from electron-prebuilt
using fluent-ffmpeg
Electron version 1.2.5

ffmpeg in root directory:

```
ffmpeg version 3.1 Copyright (c) 2000-2016 the FFmpeg developers built with Apple LLVM version 7.0.2 (clang-700.1.81) configuration: 
--prefix=/usr/local/Cellar/ffmpeg/3.1 --enable-shared --enable-pthreads --enable-gpl --enable-version3 --enable-hardcoded-tables --enable-avresample --cc=clang --host-cflags= --host-ldflags= --enable-opencl --enable-libx264 --enable-libmp3lame --enable-libxvid --disable-lzma --enable-vda
  libavutil      55. 27.100 / 55. 27.100
  libavcodec     57. 48.101 / 57. 48.101
  libavformat    57. 40.101 / 57. 40.101
  libavdevice    57.  0.101 / 57.  0.101
  libavfilter     6. 46.102 /  6. 46.102
  libavresample   3.  0.  0 /  3.  0.  0
  libswscale      4.  1.100 /  4.  1.100
  libswresample   2.  1.100 /  2.  1.100
  libpostproc    54.  0.100 / 54.  0.100
Hyper fast Audio and Video encoder
usage: ffmpeg [options] [[infile options] -i infile]... {[outfile options] outfile}...
```

Any help would be greatly appreciated.

Thanks,
Dazed and confused

**Comment by konsumer** [comment]
Yeah, the intent is to use static binaries to support the 3 major platforms, so you don't need anything else. I am on my phone now, but I will take a look when I get home.

**Comment by konsumer** [comment]
I wonder if asm.js might help make it more useful...

**Comment by konsumer** [comment]
I'm not sure I follow what the original issue was, but I will take a stab at it.

This package should go and get a copy for you from [here](https://github.com/konsumer/easy-ffmpeg/releases) automatically, if ffmpeg isn't installed on your system (in your system path.) If it is already installed, it needs to be correctly installed.

For a mac, if you want a system-wide ffmpeg installation, use [homebrew](https://brew.sh/) with `brew install ffmpeg`. This isn't needed though, as this package will install it for you, if you remove other half-installed copy of ffmpeg.

**Comment by konsumer** [comment]
Going to close, as I haven't heard back. Lemme know if the original issue persists.
