### ISSUE TITLE
Error on npm install for electron; tar.Extract is not a function

### ISSUE THREAD

**Issue by kevinpaxton-ct** [konsumer/easy-ffmpeg#7]
Observed this morning after being able to `npm install` as an electron dependency (note that this worked yesterday).

There appears to have been a problem introduced in the dependency chain for this module.

This module depends on `"tarball-extract": "0.0.3"` and that module depends on `"tar": "*"`.

The `tar` module has moved to a new version today (3.0.0) which has changed its API meaning that calls to it from `tarball-extract` now fail.  As such, I am unable to run `npm install` with the following errors:

```
> easy-ffmpeg@0.0.13 postinstall /Users/me/dev/electron-project/node_modules/easy-ffmpeg
> node install.js

/Users/me/dev/electron-project/node_modules/tarball-extract/tarball.js:11
    .pipe(tar.Extract({ path: destination}))
              ^

TypeError: tar.Extract is not a function
    at Object.extractTarball (/Users/me/dev/electron-project/node_modules/tarball-extract/tarball.js:11:15)
    at WriteStream.<anonymous> (/Users/me/dev/electron-project/node_modules/easy-ffmpeg/install.js:25:15)
    at emitNone (events.js:91:20)
    at WriteStream.emit (events.js:185:7)
    at fs.js:2017:14
    at FSReqWrap.oncomplete (fs.js:123:15)
```

I've created an issue on the `tarball-extract` github site:
#https://github.com/joshuah/tarball-extract/issues/8

If/when they correct this issue, the dependency on `tarball-extract` would need to be updated to the new, fixed version.

**Edit:** a workaround for now seems to be to add an explicit dependency on `"tar": "2.2.1"` in our electron project, meaning that the `tarball-extract` module will use that.

**Comment by konsumer** [comment]
Thanks for the report. I will update the dependency when I get back to my computer.

**Comment by konsumer** [comment]
Deposit=dependency. Sorry, on phone.

**Comment by konsumer** [comment]
Published on npm as `easy-ffmpeg@0.0.14`

**Comment by jaderkayque** [comment]
I have the same issue and I found the solution, you should follow my steps.
Open the folder where node was installed and go to this folder "...\nodejs\node_modules\npm\lib\utils"
Open the file tar.js with a notepad as an Administrator.
Go to line 385 and change the text tar.Extract to tar.extract
Go to line 395 and do the same thing, tar.Extract to tar.extract
Finally save the file and be happy.

**Comment by jaderkayque** [comment]
you should open this file and change the text tar.Extract to tar.extract and you'll solve the problem
